version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: 'postgres'
    build: './postgres'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '123'
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ft_transcendance

  backend:
    image: 'backend'
    build: './backend'
    container_name: 'backend'
    restart: 'unless-stopped'
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    depends_on:
      - postgres
    networks:
      - ft_transcendance

networks:
  ft_transcendance:
    name: ft_transcendance
    driver_opts:
      type: bridge
volumes:
  pgdata:
# #   backend:
# #     name: backend
# #     driver: local
# #     driver_opts:
# #       type: none
# #       device: /backend
# #       o: bind
# _________________________________________________________________________
# version: '3.8'

# services:
#   db:
#     image: postgres:13
#     container_name: postgres_db
#     environment:
#       POSTGRES_DB: mydatabase
#       POSTGRES_USER: myuser
#       POSTGRES_PASSWORD: mypassword
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"

#   backend:
#     build: './backend'
#     container_name: 'backend'
#     restart: 'always'
#     volumes:
#       - ./backend:/app
#     ports:
#       - 8000:8000
#     depends_on:
#       - db
#     # environment:
#     #   - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydatabase

# volumes:
#   pgdata:
# #     name: backend
# #     driver: local
# #     driver_opts:
# #       type: none
# #       device: /backend
# #       o: bind