# Generated by Django 4.2.14 on 2024-08-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0002_user_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
    ]
