version: '3.8'

services:

  backend:
    image: 'backend'
    build: './backend'
    container_name: 'backend'
    restart: 'always'
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000

    # depends_on:
    #   - postgres
    # networks:
    #   - ft_transcendance



  # postgres:
  #   image: postgres:13
  #   container_name: 'postgres'
  #   build: './postgres'
  #   environment:
  #     POSTGRES_DB: postgres
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: '123'
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - ft_transcendance

# networks:
#   ft_transcendance:
#     name: ft_transcendance
#     driver_opts:
#       type: bridge
# volumes:
#   pgdata: